name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v2
      with:
        path: "./llvm"
        key: llvm-12
        
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        directory: "./llvm"
        version: "12"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
        
    - name: List LLVM contents
      run: ls ./llvm/bin/

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=${{ env.LLVM_PATH }}\bin\clang.exe -DCMAKE_CXX_COMPILER=${{ env.LLVM_PATH }}\bin\clang++.exe -G Ninja

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        path: ${{github.workspace}}/build/Release/HiroTest.exe
      
